import React,{useRef,useMemo,useEffect,useState} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls} from 'https://esm.sh/@react-three/drei@9.114.3/core/OrbitControls.js?external=react,react-dom,three,@react-three/fiber';
import {OrthographicCamera} from 'https://esm.sh/@react-three/drei@9.114.3/core/OrthographicCamera.js?external=react,react-dom,three,@react-three/fiber';
import {PerspectiveCamera} from 'https://esm.sh/@react-three/drei@9.114.3/core/PerspectiveCamera.js?external=react,react-dom,three,@react-three/fiber';
import {Stars} from 'https://esm.sh/@react-three/drei@9.114.3/core/Stars.js?external=react,react-dom,three,@react-three/fiber';
import * as THREE from 'three';
import {useScene,demo} from './store.js';
const h=React.createElement;
const mat=(color,extra={})=>h('meshStandardMaterial',{color,flatShading:true,roughness:.85,...extra});
function mesh(geometry,args,color,position=[0,0,0],scale=[1,1,1],rotation=[0,0,0],extra={}){return h('mesh',{position,scale,rotation,castShadow:true,receiveShadow:true,...extra},h(geometry,{args}),mat(color));}
const box=(p,s,c,r=[0,0,0])=>mesh('boxGeometry',[1,1,1],c,p,s,r);
const cone=(p,r,ht,c,segments=7)=>mesh('coneGeometry',[r,ht,segments],c,p);
const cylinder=(p,top,bottom,height,c,segments=7,rotation=[0,0,0])=>mesh('cylinderGeometry',[top,bottom,height,segments],c,p,[1,1,1],rotation);
function Pine(){return h('group',null,cylinder([0,1,0],.13,.22,2,'#67462d'),cone([0,2.1,0],1.15,2,'#235949'),cone([0,2.85,0],.9,1.8,'#30715c'),cone([0,3.55,0],.64,1.65,'#43806a'));}
function Tree(){return h('group',null,cylinder([0,1.1,0],.18,.28,2.2,'#73503c'),mesh('icosahedronGeometry',[1.4,0],'#718d4b',[0,2.7,0],[1,1.1,1]),mesh('icosahedronGeometry',[.95,0],'#89a459',[.8,2.2,.2]));}
function Gable({width=3.2,height=1.4,depth=3.2,color='#4a5555',position=[0,1.98,-1.6]}){const shape=useMemo(()=>{const s=new THREE.Shape();s.moveTo(-width/2,0);s.lineTo(0,height);s.lineTo(width/2,0);s.closePath();return s;},[width,height]);return h('mesh',{position,castShadow:true,receiveShadow:true},h('extrudeGeometry',{args:[shape,{depth,bevelEnabled:false}]}),mat(color));}
function House(){return h('group',null,box([0,1,0],[2.7,2,2.6],'#9b7451'),...Array.from({length:7},(_,i)=>box([0,.25+i*.27,1.32],[2.8,.07,.06],'#674b36')),h(Gable),box([0,.7,1.36],[.6,1.4,.09],'#493f33'),box([.82,1.15,1.38],[.6,.6,.06],'#ffca77'),box([.82,1.15,1.43],[.045,.64,.02],'#594b37'),box([.82,1.15,1.43],[.64,.045,.02],'#594b37'),box([-1.35,1.15,.1],[.035,.65,.65],'#ffc67d'),box([.8,3,-.65],[.4,1.4,.5],'#767470'),box([0,.08,1.65],[1.1,.16,.7],'#a29175'));}
function Tent(){return h('group',null,h(Gable,{width:2.6,height:1.8,depth:2.5,color:'#d59b52',position:[0,.02,-1.25]}),h(Gable,{width:1.7,height:1.45,depth:.025,color:'#514739',position:[0,.025,1.26]}),cylinder([0,.85,1.3],.035,.035,1.7,'#e0c59e'),box([0,.02,0],[2.7,.04,2.9],'#877b54'));}
function Fire(){const flame=useRef();useFrame(({clock})=>{if(flame.current){flame.current.scale.set(1+Math.sin(clock.elapsedTime*8)*.08,1+Math.sin(clock.elapsedTime*11)*.16,1);}});return h('group',null,...Array.from({length:8},(_,i)=>mesh('dodecahedronGeometry',[.24,0],'#747c76',[Math.cos(i*Math.PI/4)*.65,.14,Math.sin(i*Math.PI/4)*.65],[1,.65,1])),cylinder([0,.2,0],.12,.12,1,'#69442c',6,[0,0,Math.PI/2]),cylinder([0,.3,0],.12,.12,1,'#785338',6,[Math.PI/2,0,.4]),h('group',{ref:flame},h('mesh',{position:[0,.75,0]},h('coneGeometry',{args:[.34,1.1,5]}),mat('#ff9235',{emissive:'#ff6500',emissiveIntensity:2})),h('mesh',{position:[.13,.52,.13]},h('coneGeometry',{args:[.19,.65,5]}),mat('#ffe495',{emissive:'#ffbc45',emissiveIntensity:3}))),h('pointLight',{position:[0,1,0],color:'#ff973e',intensity:9,distance:8,decay:2}));}
function Bridge(){return h('group',null,...Array.from({length:14},(_,i)=>box([-2.05+i*.315,.38+Math.sin(i/13*Math.PI)*.15,0],[.29,.16,1.55],i%2?'#b49b72':'#a38a63')),...[-1,1].flatMap(side=>[-1.95,-.65,.65,1.95].map(x=>box([x,.85,side*.83],[.12,1.3,.12],'#826746'))),...[-1,1].map(side=>box([0,1.4,side*.83],[4.2,.11,.11],'#ad926a')));}
function River(){const shape=useMemo(()=>{const s=new THREE.Shape();s.moveTo(-1.3,-12);for(let z=-12;z<=12;z+=.5)s.lineTo(Math.sin(z*.38)*.8-1.3,z);for(let z=12;z>=-12;z-=.5)s.lineTo(Math.sin(z*.38)*.8+1.3,z);s.closePath();return s;},[]);const shimmer=useRef();useFrame(({clock})=>{if(shimmer.current)shimmer.current.position.z=Math.sin(clock.elapsedTime*.35)*.2;});return h('group',null,h('mesh',{rotation:[-Math.PI/2,0,0],position:[0,.075,0],receiveShadow:true},h('shapeGeometry',{args:[shape]}),mat('#67b3b4',{roughness:.25,metalness:.25})),h('group',{ref:shimmer},...Array.from({length:30},(_,i)=>box([Math.sin(i*1.9)*.8+Math.sin((i*.77-11)*.38)*-.8,.085,i*.77-11],[.25+(i%3)*.19,.007,.028],'#a2d9d1'))));}
function Mountain(){return h('group',null,cone([0,1.3,0],2.1,2.7,'#687b73',5),cone([0,2.3,0],.59,.78,'#d8dfcc',5),cone([1.05,.65,.7],1.25,1.6,'#788771',5));}
function Tower(){return h('group',null,cylinder([0,2,0],.65,1,4,'#d7c8a4',8),cylinder([0,4.2,0],1,1,.6,'#6a6555',8),cone([0,5,0],1.15,1,'#985d48',8),box([0,4.2,.98],[.6,.42,.025],'#ffd187'),box([0,.6,.93],[.5,1.2,.05],'#5b4c3c'));}
function Cloud(){return h('group',null,...[[0,0,0],[1,.2,0],[-.9,-.15,0],[.3,.1,.5]].map((p,i)=>mesh('icosahedronGeometry',[.8,1],'#dce2d6',p,[1.35,.55,.8],undefined,{castShadow:false})));}
function Model({type}){switch(type){case 'pine_tree':return h(Pine);case 'tree':return h(Tree);case 'house':return h(House);case 'tent':return h(Tent);case 'campfire':return h(Fire);case 'bridge':return h(Bridge);case 'river':return h(River);case 'mountain':return h(Mountain);case 'tower':return h(Tower);case 'cloud':return h(Cloud);case 'road':return box([0,.09,0],[15,.03,1.3],'#b9a681');default:return mesh('dodecahedronGeometry',[.75,0],'#8e9891',[0,.36,0],[1.2,.75,1]);}}
function SceneObject({object,interactive}){const selected=useScene(s=>s.selected===object.id);const select=useScene(s=>s.select);const [hover,setHover]=useState(false);return h('group',{position:object.position,scale:object.scale,onClick:interactive?e=>{e.stopPropagation();select(object.id);}:undefined,onPointerOver:interactive?e=>{e.stopPropagation();setHover(true);document.body.style.cursor='pointer';}:undefined,onPointerOut:()=>{setHover(false);document.body.style.cursor='auto';}},h(Model,{type:object.type}),(selected||hover)&&h('mesh',{rotation:[-Math.PI/2,0,0],position:[0,.12,0]},h('ringGeometry',{args:[1.05,selected?1.13:1.09,48]}),h('meshBasicMaterial',{color:selected?'#bbdeff':'#e4f2e3',transparent:true,opacity:selected?.95:.5,depthTest:false})));}
function Terrain({kind='meadow'}){const ref=useRef();const desert=kind==='desert';useEffect(()=>{const dummy=new THREE.Object3D();let n=0;for(let i=0;i<400;i++){const a=i*2.39996,r=Math.sqrt((i+.5)/400)*20,x=Math.cos(a)*r,z=Math.sin(a)*r;if(Math.abs(x+Math.sin(z*.38)*.8)<1.8)continue;dummy.position.set(x,.14,z);dummy.rotation.set(0,i,Math.sin(i)*.12);dummy.scale.set(.07,.15+(i%4)*.07,.07);dummy.updateMatrix();ref.current.setMatrixAt(n++,dummy.matrix);}ref.current.count=n;ref.current.instanceMatrix.needsUpdate=true;},[]);return h('group',null,kind==='island'&&cylinder([0,-1.3,0],40,40,.1,'#408d97',64),cylinder([0,-.55,0],22,21.5,1.15,desert?'#b99466':'#596244',12),cylinder([0,-1.15,0],21.5,20,.5,desert?'#98734f':'#4a4837',12),cylinder([0,-.08,0],22,22,.14,desert?'#d2b280':'#879562',12),h('instancedMesh',{ref,args:[null,null,400],castShadow:true},h('coneGeometry',{args:[1,1,3]}),mat(desert?'#a99160':'#617d4c')),...Array.from({length:40},(_,i)=>{const z=i*.88-17.5;return mesh('dodecahedronGeometry',[.23+(i%3)*.06,0],'#a6ac92',[(i%2?1:-1)*1.5-Math.sin(z*.38)*.8,.1,z],[1.2,.6,1]);}));}
function Precipitation({weather}){const isSnow=weather==='snow';const count=isSnow?900:1100;const spread=46;const height=26;const ref=useRef();const positions=useMemo(()=>{const a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3]=(Math.random()-.5)*spread;a[i*3+1]=Math.random()*height;a[i*3+2]=(Math.random()-.5)*spread;}return a;},[count,spread,height]);useFrame((_,dt)=>{if(!ref.current)return;const p=ref.current.geometry.attributes.position;const speed=isSnow?3.2:18;for(let i=0;i<count;i++){if(isSnow)p.array[i*3]+=Math.sin(i*7+p.array[i*3+1]*.3)*.035;p.array[i*3+1]-=dt*speed;if(p.array[i*3+1]<0){p.array[i*3+1]=height;p.array[i*3]=(Math.random()-.5)*spread;p.array[i*3+2]=(Math.random()-.5)*spread;}}p.needsUpdate=true;});return h('points',{ref},h('bufferGeometry',null,h('bufferAttribute',{attach:'attributes-position',array:positions,count,itemSize:3})),h('pointsMaterial',{color:isSnow?'#ffffff':'#aed6f1',size:isSnow?3.5:1.8,sizeAttenuation:false,transparent:true,opacity:isSnow?.95:.8,depthWrite:false}));}
function Walk(){const {camera,gl}=useThree();const keys=useRef({});const velocity=useRef(0);const yaw=useRef(0);const pitch=useRef(0);useEffect(()=>{camera.position.set(7,1.8,10);camera.rotation.order='YXZ';yaw.current=.55;const down=e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;keys.current[e.code]=true;if(e.code==='Space'&&document.pointerLockElement){e.preventDefault();if(camera.position.y<=1.81)velocity.current=5;}};const up=e=>keys.current[e.code]=false;const mouse=e=>{if(document.pointerLockElement!==gl.domElement)return;yaw.current-=e.movementX*.002;pitch.current=Math.max(-1.4,Math.min(1.4,pitch.current-e.movementY*.002));};const click=()=>{if(!gl.domElement.requestPointerLock){window.dispatchEvent(new CustomEvent('sceneforge:notice',{detail:'Mouse-look is unavailable here. Use Orbit mode instead.'}));return;}try{gl.domElement.requestPointerLock()?.catch?.(()=>window.dispatchEvent(new CustomEvent('sceneforge:notice',{detail:'Mouse-look is blocked in this preview. Open the published site or use Orbit mode.'})));}catch{window.dispatchEvent(new CustomEvent('sceneforge:notice',{detail:'Mouse-look is blocked. Use Orbit mode instead.'}));}};const blur=()=>keys.current={};document.addEventListener('keydown',down);document.addEventListener('keyup',up);document.addEventListener('mousemove',mouse);window.addEventListener('blur',blur);gl.domElement.addEventListener('click',click);return ()=>{document.removeEventListener('keydown',down);document.removeEventListener('keyup',up);document.removeEventListener('mousemove',mouse);window.removeEventListener('blur',blur);gl.domElement.removeEventListener('click',click);if(document.pointerLockElement)document.exitPointerLock();};},[camera,gl]);useFrame((_,delta)=>{if(document.pointerLockElement!==gl.domElement)return;const dt=Math.min(delta,.04),k=keys.current;const forward=(k.KeyW?1:0)-(k.KeyS?1:0),right=(k.KeyD?1:0)-(k.KeyA?1:0),speed=(k.ShiftLeft||k.ShiftRight?7:3.5)*dt/Math.max(1,Math.hypot(forward,right));camera.position.x+=(-Math.sin(yaw.current)*forward+Math.cos(yaw.current)*right)*speed;camera.position.z+=(-Math.cos(yaw.current)*forward-Math.sin(yaw.current)*right)*speed;camera.position.x=THREE.MathUtils.clamp(camera.position.x,-20,20);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-20,20);velocity.current-=12*dt;camera.position.y=Math.max(1.8,camera.position.y+velocity.current*dt);camera.rotation.set(pitch.current,yaw.current,0);});return null;}
const lightSettings={morning:{bg:'#283b3b',sun:'#fff1d5',ambient:1.6,intensity:3,pos:[-14,20,-6],sunPos:[-2,10,-18],sunColor:'#ffefa8',sunSize:2.8},afternoon:{bg:'#293b40',sun:'#fff6e5',ambient:1.8,intensity:3.5,pos:[10,22,6],sunPos:[5,11,-18],sunColor:'#fffde0',sunSize:2.9},sunset:{bg:'#2a3536',sun:'#ffd49b',ambient:1.4,intensity:3.8,pos:[-18,14,6],sunPos:[-4,7.5,-16],sunColor:'#ff9436',sunSize:3.3},night:{bg:'#111d2b',sun:'#91baff',ambient:.5,intensity:1,pos:[8,15,-8],sunPos:[4,10,-18],sunColor:'#d0e2ff',sunSize:2.2}};
function SunMesh({position,color,size}){return h('group',{position},h('mesh',null,h('sphereGeometry',{args:[size,16,16]}),h('meshStandardMaterial',{color,emissive:color,emissiveIntensity:2,roughness:0.2})),h('mesh',null,h('sphereGeometry',{args:[size*1.3,12,12]}),h('meshBasicMaterial',{color,transparent:true,opacity:.2})));}
function World({preview}){const currentScene=useScene(s=>s.scene);const previewScene=useMemo(()=>demo(),[]);const scene=preview?previewScene:currentScene;const mode=useScene(s=>s.mode);const rev=useScene(s=>s.revision);const {size}=useThree();const env=scene.environment;const l=lightSettings[env.time];const isFog=env.weather==='fog';const dark=['rain','cloudy','snow'].includes(env.weather);const isNight=env.time==='night';const fogColor=isFog?'#8aada8':l.bg;const bgColor=isFog?'#6d8f8c':l.bg;return h(React.Fragment,null,h('color',{attach:'background',args:[bgColor]}),h('fog',{attach:'fog',args:[fogColor,isFog?18:90,isFog?58:200]}),h('ambientLight',{intensity:l.ambient*(dark?.65:1)*(isFog?.75:1),color:'#d5e1db'}),h('hemisphereLight',{args:['#b6d7df','#83844f',1]}),h('directionalLight',{position:l.pos,color:l.sun,intensity:l.intensity*(dark?.4:1)*(isFog?.5:1),castShadow:true,'shadow-mapSize':[2048,2048],'shadow-camera-left':-30,'shadow-camera-right':30,'shadow-camera-top':30,'shadow-camera-bottom':-30,'shadow-normalBias':.06}),!dark&&!isFog&&h(SunMesh,{position:l.sunPos,color:l.sunColor,size:l.sunSize}),mode==='walk'&&!preview?h(React.Fragment,null,h(PerspectiveCamera,{makeDefault:true,fov:65,near:.1,far:250}),h(Walk)):h(React.Fragment,null,h(OrthographicCamera,{makeDefault:true,position:[28,24,34],zoom:Math.min(size.width/42,size.height/28),near:.1,far:300}),h(OrbitControls,{key:rev,makeDefault:true,target:[0,2,0],enableDamping:true,dampingFactor:.07,enablePan:!preview,minZoom:5,maxZoom:95,maxPolarAngle:Math.PI/2.1,minPolarAngle:.25,autoRotate:preview&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches,autoRotateSpeed:.22})),h(Terrain,{kind:scene.terrain}),...scene.objects.map(o=>h(SceneObject,{key:o.id,object:o,interactive:!preview})),['rain','snow'].includes(env.weather)&&h(Precipitation,{weather:env.weather}),env.weather==='cloudy'&&h('group',{position:[0,9,0],scale:2},h(Cloud)),isNight&&h(Stars,{radius:80,depth:30,count:900,factor:3,fade:true,speed:.3}));}
export function Scene({preview=false}){return h(Canvas,{shadows:true,dpr:[1,1.65],gl:{antialias:true,alpha:false},onPointerMissed:()=>useScene.getState().select(null),fallback:h('div',{className:'canvas-error'},'WebGL is unavailable. Open SceneForge in a browser with hardware acceleration enabled.')},h(World,{preview}));}
