import {create} from 'zustand';
import {editSceneWithAI} from './ai.js';
export const TYPES=['tree','pine_tree','rock','house','tent','campfire','bridge','river','mountain','tower','road','cloud'];
export const TIMES=['morning','afternoon','sunset','night'];
export const WEATHER=['clear','cloudy','rain','snow','fog'];
export const label=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const obj=(type,x,z,scale=1,y=0)=>({id:crypto.randomUUID(),type,position:[x,y,z],scale});
export function demo(){return {name:'Mountain Camp',objects:[obj('river',0,0),obj('house',-4.8,-3,1.25),obj('bridge',.8,1.5,1.2),obj('tent',4,4,1.1),obj('campfire',3,1.6),obj('pine_tree',-8,-1,1.5),obj('pine_tree',-7,-5,1.7),obj('pine_tree',-2.6,-6,1.35),obj('pine_tree',5,-4,1.75),obj('pine_tree',7,-1,1.4),obj('pine_tree',-6,5,.95),obj('pine_tree',7,5,1.1),obj('mountain',-5,-9,2.5),obj('mountain',1,-10,3),obj('mountain',7,-8,2),obj('rock',-2.5,4,.8),obj('rock',2,-3,.8),obj('rock',5.2,2,.6),obj('rock',-8,4,.6),obj('rock',8,-4,1),obj('cloud',-7,-5,1,10),obj('cloud',6,-8,1.1,12)],environment:{weather:'clear',time:'sunset'}};}
export function validateScene(scene){if(!scene||!Array.isArray(scene.objects)||scene.objects.length>200||!TIMES.includes(scene.environment?.time)||!WEATHER.includes(scene.environment?.weather))throw Error('Invalid scene structure.');const ids=new Set();for(const o of scene.objects){if(typeof o.id!=='string'||ids.has(o.id)||!TYPES.includes(o.type)||!Array.isArray(o.position)||o.position.length!==3||!o.position.every(v=>Number.isFinite(v)&&Math.abs(v)<=100)||!Number.isFinite(o.scale)||o.scale<.1||o.scale>8)throw Error('Invalid object data.');ids.add(o.id);}return scene;}
const initialScene=demo();
export const useScene=create((set,get)=>({scene:initialScene,baseline:structuredClone(initialScene),selected:null,history:[],revision:0,mode:'orbit',setMode:mode=>set({mode}),select:selected=>set({selected}),load:scene=>set({scene:validateScene(scene),baseline:structuredClone(scene),selected:null,history:[],revision:get().revision+1,mode:'orbit'}),environment:patch=>set(s=>({scene:validateScene({...s.scene,environment:{...s.scene.environment,...patch}})})),remove:id=>set(s=>({scene:{...s.scene,objects:s.scene.objects.filter(o=>o.id!==id)},selected:s.selected===id?null:s.selected})),execute:command=>{const s=get();const {scene,message}=parseCommand(command,s.scene,s.selected);validateScene(scene);set({scene,selected:scene.objects.some(o=>o.id===s.selected)?s.selected:null,history:[...s.history,{command,message}].slice(-20)});return message;},executeAI:async(command,apiKey)=>{const s=get();const {scene,message}=await editSceneWithAI(command,s.scene,s.selected,apiKey);validateScene(scene);set({scene,selected:scene.objects.some(o=>o.id===s.selected)?s.selected:null,history:[...s.history,{command,message}].slice(-20)});return message;}}));
const aliases=[['pine_tree',/pine(?:\s+tree)?s?/],['campfire',/(?:campfire|fire)/],['bridge',/bridge/],['river',/river/],['mountain',/mountain/],['house',/(?:house|cabin)/],['tent',/tent/],['tower',/(?:tower|lighthouse)/],['road',/(?:road|path)/],['cloud',/cloud/],['rock',/(?:rock|stone)/],['tree',/tree/]];
function typeIn(s){return aliases.find(([,re])=>re.test(s))?.[0];}
export function parseCommand(raw,current,selected){const text=raw.toLowerCase().trim();let scene=structuredClone(current);if(!text)throw Error('Type a command to shape your scene.');
const weather=text.match(/\b(clear|cloudy|rainy|rain|snowy|snow|foggy|fog)\b/);const time=text.match(/\b(morning|afternoon|sunset|night)\b/);
if(!/^(add|create|place|remove|delete|move)\b/.test(text)&&(weather||time)){if(weather)scene.environment.weather=({rainy:'rain',snowy:'snow',foggy:'fog'})[weather[1]]||weather[1];if(time)scene.environment.time=time[1];return {scene,message:`Environment updated · ${label(scene.environment.time)} / ${label(scene.environment.weather)}`};}
if(/^(how many|list|what|count|show)/.test(text)){const t=typeIn(text);const n=scene.objects.filter(o=>!t||o.type===t).length;return {scene,message:`This scene contains ${n} ${t?label(t).toLowerCase()+' objects':'objects'}.`};}
const action=text.match(/^(add|create|place|remove|delete|move)\b/)?.[1];if(!action)throw Error('Local mode supports “Add a pine tree”, “Remove the rock near the campfire”, “Make it rainy”, and “Make it sunset”. Free-form AI is not connected.');
const parts=text.split(/\b(?:near|beside|by|across|next to)\b/);const type=typeIn(parts[0]);const anchorType=typeIn(parts[1]||'');const anchor=scene.objects.find(o=>o.type===anchorType);if(anchorType&&!anchor)throw Error(`There is no ${label(anchorType).toLowerCase()} to place an object near.`);
if(['add','create','place'].includes(action)){if(!type)throw Error('Choose a supported object: tree, pine tree, rock, house, tent, campfire, bridge, river, mountain, tower, road, or cloud.');if(scene.objects.length>=200)throw Error('This world is full (200 objects). Remove an object first.');const countWord=parts[0].match(/\b(\d+|two|three|four|five|six|seven|eight|nine|ten)\b/)?.[1];const count=Math.min(15,Math.max(1,Number(countWord)||({two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10})[countWord]||1));if(scene.objects.length+count>200)throw Error('That would exceed the 200-object scene limit.');for(let i=0;i<count;i++){const a=scene.objects.length*2.399+i;let x=Math.cos(a)*10,z=Math.sin(a)*10;if(anchor){x=anchor.position[0]+2.4+i*1.5;z=anchor.position[2]+1.6;if(type==='bridge'&&anchor.type==='river'){x=anchor.position[0]+.8;z=anchor.position[2]+1.5;}}scene.objects.push(obj(type,Math.max(-20,Math.min(20,x)),Math.max(-20,Math.min(20,z)),1,type==='cloud'?12:0));}return {scene,message:`Added ${count===1?'a':count} ${label(type).toLowerCase()}${anchor?' near the '+label(anchor.type).toLowerCase():''}.`};}
let candidates=scene.objects.filter(o=>text.includes('selected')?o.id===selected:o.type===type);if(anchor)candidates.sort((a,b)=>distance(a,anchor)-distance(b,anchor));const target=candidates[0];if(!target)throw Error('No matching object found. Select an object or specify its type.');if(action==='move'){if(!anchor)throw Error('Try “Move the tent near the house”.');target.position=[anchor.position[0]+2.5,target.position[1],anchor.position[2]+2];return {scene,message:`Moved ${label(target.type).toLowerCase()}.`};}scene.objects=scene.objects.filter(o=>o.id!==target.id);return {scene,message:`Removed ${label(target.type).toLowerCase()}.`};}
function distance(a,b){return a.position.reduce((sum,v,i)=>sum+(v-b.position[i])**2,0);}
export function localScene(prompt){const text=prompt.toLowerCase();if(!aliases.some(([,re])=>re.test(text))&&!/camp|village|island|desert/.test(text))throw Error('Local builder didn’t recognize a supported scene or object. Try an example prompt. Free-form AI generation is not connected.');let s=demo();s.terrain=/desert/.test(text)?'desert':/island/.test(text)?'island':'meadow';s.name=prompt.trim().slice(0,48)||'Untitled scene';s.objects=s.objects.filter(o=>(s.terrain==='island'?['rock','cloud']:['mountain','rock','cloud']).includes(o.type));let n=0;for(const [type,re] of aliases){if(re.test(text)&&!(type==='tree'&&/pine/.test(text))){const countMatch=text.match(new RegExp('\\b(\\d+|one|two|three|four|five)\\s+(?:pine\\s+)?'+(type==='pine_tree'?'trees?':type.replace('_',' ')+'s?')+'\\b'));const counts={one:1,two:2,three:3,four:4,five:5};const count=Math.min(8,countMatch?(Number(countMatch[1])||counts[countMatch[1]]):['pine_tree','tree'].includes(type)?5:1);for(let i=0;i<count;i++){let x=Math.cos(n*2.4)*6,z=Math.sin(n*2.4)*5;if(type==='river'){x=0;z=0;}if(type==='bridge'){x=.8;z=1.5;}s.objects.push(obj(type,x,z,1,type==='cloud'?10:0));n++;}}}if(/village/.test(text)){for(let i=0;i<4;i++)s.objects.push(obj('house',-6+i*4,-2+(i%2)*5));s.objects.push(obj('road',0,0));}if(/camp/.test(text)&&!s.objects.some(o=>o.type==='tent'))s.objects.push(obj('tent',4,4),obj('campfire',3,1));const time=TIMES.find(t=>text.includes(t));if(time)s.environment.time=time;const w=WEATHER.find(t=>text.includes(t));if(w)s.environment.weather=w;return validateScene(s);}
